### ISSUE TITLE
Entries in configuration section are doubled in few cases

### ISSUE THREAD

**Issue by Alphanumerix** [sharvil/api-docs#24]
I believe it's related to versioning.
Problem touches languages like Clojure (2), Django (2), Node.js (2), and Symfony (3).

**Comment by tortuetorche** [comment]
:+1: 
And also for Ruby

**Comment by dirk-thomas** [comment]
The settings pages currently has several quirks:

1. The `Theme` configuration is mixed in the long list of languages.

2. Upper case languages like `HTML` are rendered with spaces before each upper case letter: `H T M L`.

3. Multiple entries for different versions of the same language are indistinguishable since the version number is not part of the label:

  * Clojure~1
    * [ ] Clojure
    * [ ] Clojure

4. Some group names contain `~` in the label, e.g. `Clojure~1`.

5. If for a language multiple major versions exist the grouping is per major version - not per language:

  * Python~2
    * [ ] Python
  * Python~3
    * [ ] Python

No. 5 is due to the fact that the `slug` name of the language is being used as the configuration key. Since it commonly uses `~` to separate the language name from the version and then the version number uses `.` to separate the different version parts I don't see a good way to change this without changing the configuration key (which would break existing configurations).

For the four other issues I have created PR #26 to fix them.

**Comment by dirk-thomas** [comment]
This has been addressed by #26.
