### ISSUE TITLE
Can't find language selection in settings

### ISSUE THREAD

**Issue by alanzanattadev** [sharvil/api-docs#33]
Hi,

I've installed api-docs 0.0.5, and I only have the theme setting in settings panel of this package, but there's no option to select frameworks and languages we want to enable, is it normal ?

I have keybindings activation setting too.

Thank you

**Comment by dirk-thomas** [comment]
Can you please provide more information like the version numbers of `Atom` and `settings-view`. And what platform you are on. I assume you have an internet connection to fetch the available languages from devdocs.io? Have you tried to close / reopen the editor, or to reinstall the package?

**Comment by alanzanattadev** [comment]
The problem has disparreared and everthing is displayed correctly from now, I'm sorry for the useless issue, maybe I had to reload Atom one or many times ? :) Thank you btw

**Comment by tibaes** [comment]
Just to provide a feedback, I got the same issue and it was solved reinstalling the package.

**Comment by nnals** [comment]
hello.

i just had the same issue and it also resolved by reinstalling. i'm running atom 1.18.0 and settings-view 0.249.4.

if this issue is hard to fix right now, maybe you could consider adding a little note to the README that reinstalling fixes it. i almost uninstalled the package completely and there might be some who walk away not being able to enjoy this wonderful package.
